version: "3.8"
services:
    nginx:
        image: nginx:latest
        container_name: start_avito_nginx
        depends_on: 
            - start-avito-app
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./html/index/:/etc/nginx/data/www/subscribe/
            - ./nginx/index.html:/etc/nginx/html/index.html
        ports:
            - 80:80
            - 443:443

    start-avito-app:
        image: golang:1.15-alpine
        container_name: start-avito-app
        ports:
            - 8080:80
        volumes:
            - ./go:/app
        working_dir: /app
        command: go run main.go
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3